name: Surge Action
on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
  
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    
      with:
        node-version: '12.x'
        
    - name: check commands
      run: pwd
      
    - name: checking up the list
      run: ls
      
    - name: Install surge
      run : npm install -g surge
      
    - name: Deploy the website
      run: surge ./ https://mere-divisio122n.surge.sh/ --token ${{secrets.TESTING_SURGE_TOKEN}}
